# Generated by Django 4.0.3 on 2022-05-05 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Рейтинг не может быть меньше 0')]),
        ),
    ]
